### ISSUE TITLE
--auditor - Fatal error: Program execution stopped due to security measure

### ISSUE THREAD

**Issue by aztrix** [CISOfy/lynis#1645]
**Describe the bug**
I'm trying to use lynis with the --auditor option but it causes the following error i.e  lynis audit system --auditor "Joe Blow":
Execution of Lynis stopped as we found unexpected input or invalid characters in argument 4
Do you believe this is in error? Let us know: lynis-dev@cisofy.com

Fatal error: Program execution stopped due to security measure

When I run lynis audit system --auditor "JoeBlow" it works without a problem, so it's not the quotes causing the problem but the space

**Version**
 - Distribution openSUSE Tumbleweed-Slowroll (20250701)
 - Lynis version 3.1.5 (and 3.1.4)

**Expected behaviour**
Expect program to work as per documentation i.e. complete with documented --parameters
e.g lynis audit system --auditor "Joe Blow" should be accepted and should result in Auditor: Joe Blow 

**Output**
No lynis.log, expect Auditor: Joe Blow

**Additional context**
This is on a local install of lynis 3.1.5 because of the egrep error in 3.1.4 but also occurs on 3.1.4

Let me know what diagnostics you require to fix this?

**Comment by mboelen** [comment]
Fixed with commit https://github.com/CISOfy/lynis/commit/76a4f4dfd8b389d20a3da0c6dd8de9a801f2f73c

Can you test if that is the case?

**Comment by mboelen** [comment]
Thanks for validating it. With that, I will close this issue.

@aztrix Would be great if you could test it too (as you are the reporter of the issue). Also fine if you wait for the next release and then validate that it is has been resolved.

**Comment by aztrix** [comment]
Please forgive me if I'm doing this incorrectly but I am willing to learn

I ran:
```
**git fetch --verbose --progress**
POST git-upload-pack (214 bytes)
POST git-upload-pack (964 bytes)
remote: Enumerating objects: 154, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 154 (delta 36), reused 31 (delta 30), pack-reused 107 (from 2)
Receiving objects: 100% (154/154), 184.88 KiB | 830.00 KiB/s, done.
Resolving deltas: 100% (91/91), completed with 16 local objects.
From https://github.com/CISOfy/lynis
   44c41bc..fb45fdd  master                                 -> origin/master
 = [up to date]      revert-1450-fix/apk-PackageIsInstalled -> origin/revert-1450-fix/apk-PackageIsInstalled
 * [new tag]         3.1.5                                  -> 3.1.5

**lynis audit system --auditor "Joe Blow"**
```

Still getting Fatal error: Program execution stopped due to security measure

Should I delete and redo a full clone?
