### ISSUE TITLE
Ubuntu 18.04 NetPlan - problem with 2 responsive nameservers 

### ISSUE THREAD

**Issue by Vilican** [CISOfy/lynis#545]
Ubuntu 18.04 uses NetPlan + DNSMasq to configure networking and nameservers.

For example, my `/etc/netplan/01-netcfg.yaml` looks like this (IPs and domains changed):

```
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: no
      dhcp6: no
      addresses: [192.168.1.2/24]
      gateway4: 192.168.1.1
      nameservers:
        search: [example.net]
        addresses: [192.168.1.1,8.8.8.8]
```

In `resolv.conf` is added only localhost (`nameserver 127.0.0.53`). Any changes gets overwritten.

So, although I do actually have 2 responsive nameservers, I am still getting red warning NETW-2705.

**Comment by mboelen** [comment]
Fixed with commit https://github.com/CISOfy/lynis/commit/170e427595e54ad4194cf185b9643e7af786b27c

Thanks for reporting.

**Comment by freeeflyer** [comment]
@mboelen : Commited on may 1st, still not present on distribution on august 1 ?

**Comment by mboelen** [comment]
The commit is there for some time, so it is definitely available.

Are you using an older version of Lynis?


Michael Boelen
*Founder - Strategy and Development*

<https://cisofy.com/>
*E-mail: *michael.boelen@cisofy.com *or Call: *+31 637 202 238
<0031637202238>

On Mon, Jul 30, 2018 at 2:53 PM, Nicolas Zagulajew <notifications@github.com
