### ISSUE TITLE
Security repository for Raspbian

### ISSUE THREAD

**Issue by daniellukaszgmailcom** [CISOfy/lynis#835]
Lynis doesn't find a security repository for Raspbian. There isn't a security repository for Raspbian...
https://www.raspberrypi.org/forums/viewtopic.php?t=98006

cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

~/.git-lynis/lynis --version
3.0.0

! Can't find any security repository in /etc/apt/sources.list or sources.list.d directory [PKGS-7388]
      https://cisofy.com/lynis/controls/PKGS-7388/

**Comment by mboelen** [comment]
Added commit https://github.com/CISOfy/lynis/commit/6e3e93d5854960dee1e7516922647c303e4094b8 to restrict the distributions. It is resolved for you with this change?

**Comment by mboelen** [comment]
No response received, so making an assumption that it works with the mentioned commit. Will close this issue.

**Comment by daniellukaszgmailcom** [comment]
no, it is still not resolved 
(sorry for the delay, the notification was in spam folder)

**Comment by Varbin** [comment]
I can confirm, there is still a warning on a current raspbian release.

**Comment by Varbin** [comment]
If you are intered, `lynis show os` shows:

```
OS=Linux
OS_NAME=Raspbian
OS_FULLNAME=Debian 10.4
OS_VERSION=10.4
```
